### ISSUE TITLE
Remove CORS requirements to simplify Upsun config and ease of understanding app code

### ISSUE THREAD

**Issue by tylers-username** [platformsh/demo-project#13]
```[tasklist]
### Tasks
- [x] Remove cors logic form python
- [x] modify local react development package.json to proxy requests to python backend
- [x] Implement upsun backend routing as subdirectory proxy to avoid cors issues
- [x] Remove custom deploy steps around url magic
```
