### ISSUE TITLE
Show content history of completed steps in a minmal state

### ISSUE THREAD

**Issue by tylers-username** [platformsh/demo-project#41]
We've hidden the content areas because they are much longer than originally designed. This is because we do not have the `demo:start` command ready yet.

The impact of this is that it throws off the original design and the user cannot see the previous commands that they ran.
```[tasklist]
### Tasks
- [x] Show completed steps content
- [x] Collapse completed steps content
- [x] Scroll to complete steps content
```
