### ISSUE TITLE
Copy revisions

### ISSUE THREAD

**Issue by tylers-username** [platformsh/demo-project#43]
```[tasklist]
### Tasks
- [ ] Keep content as concise as possible
- [ ] Ensure copy aligns with the purpose of the demo: enable users to experience key features of Upsun
- [ ] Ensure copy aligns with: this is not a "how to use Upsun" guide—it is a "experience cool features of Upsun" guide.
- [ ] Implement ![image](https://github.com/platformsh/demo-project/assets/4887071/6580cf8f-4ee9-48df-bce0-7161c857f8ca)
- [ ] resources:set should use the minimum values possible
```
