### ISSUE TITLE
Feedback - improve copy

### ISSUE THREAD

**Issue by tylers-username** [platformsh/demo-project#52]
```[tasklist]
### Tasks
- [ ] **Remove numbers from steps section titles**. e.g. `1. Deploy to Upsun` becomes `Deploy to Upsun`
- [ ] **Because "Next steps" are numbered, remove the "Next step" title from each step.** It reduces copy while the numbered lists keep it easy for devs to skim-read to what they need to do next. _**If needed**_ for each sentence that prefixes the bullet list of steps, we can add an additional blank line ahead of it to ensure a clear separation of thought
- [ ] **Step: Create your first preview environment**: Bold the copy `Before you make your first revision, let's create a new preview environment called staging.`
- [ ] **Step: Deploy to Upsun**: "Installed the Upsun CLI" should end with a period.
- [ ] **Step: Add a Redis Service**: `Once happy, we'll commit the changes using `git` and then merge it into production.` should have a comma after `git`.
- [ ] **Step: Add a Redis Service**: `1. Create the relationship. Open `upsun/config.yaml` and uncomment the following lines` should have a comma after `.yaml` and a colon (`:`) at the end.
- [ ] **Step: Merge stating into production**: Bullet #3 should have a period (`.`) after browser
- [ ] **Step: Merge stating into production**: Transition into the steps with this copy on the line after `Use your preview environment...`. The copy is: `Now, let's take your changes to production.`
- [ ] **Step: You did it!**: `Migrate your application` should end in a period
- [ ] Reach out to content marketing team for a final walkthrough of copy.
```

**Comment by tylers-username** [comment]
@chadwcarlson - this better aligns with brand requirements. But this should probably be put on hold until the default resources changes are in place.
