### ISSUE TITLE
Add design debugger

### ISSUE THREAD

**Issue by tylers-username** [platformsh/demo-project#91]
```[tasklist]
### Tasks
- [ ] should toggle states to help walk through demo
- [ ] should be disabled by default
- [ ] should be enabled by environment cariable
```
